server:
  port: 11111

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/mong}
      auto-index-creation: true

    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  cache:
    type: caffeine
    cache-names: dailySleepSummary, recentSleepSummary
    caffeine:
      spec:
        # dailySleepSummary 캐시 설정
        dailySleepSummary: expireAfterWrite=1h,maximumSize=1000
        # recentSleepSummary 캐시 설정
        recentSleepSummary: expireAfterWrite=10m,maximumSize=500

logging:
  level:
    com.project.sleep: DEBUG  # 추가
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine: DEBUG


jwt-properties:
  key: ${JWT_KEY:KItFWMZokpiSj6ABi42XJpNWbBqUJ4UT3mhLrXk//IjI2TgQy2Bk+2KrCk4cQDl8oFsSYH9Gr++Lqr2w6CYJnQ==}
  access-token-subject: AccessToken
  refresh-token-subject: RefreshToken
  token-header: Authorization
  bearer: Bearer
  id: id

management:
  endpoints:
    web:
      exposure:
        include: health,info,liveness,readiness,prometheus
  endpoint:
    health:
      show-details: always
    liveness:
      enabled: true
    readiness:
      enabled: true
  metrics:
    tags:
      application: sleep-service
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    enabled: true
  paths-to-match:
    - /api/**